package dependency

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestGetDepFileTypeAndLanguage(t *testing.T) {
	r := NewDepFileTypeRegistry()

	typ, lang := r.GetDepFileTypeAndLanguage("cmakelists.txt")
	assert.Equal(t, LanguageID("cmake"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.cmake")
	assert.Equal(t, LanguageID("cmake"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("makefile")
	assert.Equal(t, LanguageID("makefile"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.make")
	assert.Equal(t, LanguageID("makefile"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.mkfile")
	assert.Equal(t, LanguageID("makefile"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.mak")
	assert.Equal(t, LanguageID("makefile"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.mk")
	assert.Equal(t, LanguageID("makefile"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.pro")
	assert.Equal(t, LanguageID("qmake"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.pri")
	assert.Equal(t, LanguageID("qmake"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.sln")
	assert.Equal(t, LanguageID("visual studio"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.vcxproj")
	assert.Equal(t, LanguageID("visual studio"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.vcproj")
	assert.Equal(t, LanguageID("visual studio"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.props")
	assert.Equal(t, LanguageID("visual studio"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.xcconfig")
	assert.Equal(t, LanguageID("xcode"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.pbxproj")
	assert.Equal(t, LanguageID("xcode"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.xcworkspacedata")
	assert.Equal(t, LanguageID("xcode"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.am")
	assert.Equal(t, LanguageID("automake"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.qbs")
	assert.Equal(t, LanguageID("qbs"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.ninja")
	assert.Equal(t, LanguageID("ninja"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.vcpkg")
	assert.Equal(t, LanguageID("vcpkg"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.jam")
	assert.Equal(t, LanguageID("boost.jam"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.gradle")
	assert.Equal(t, LanguageID("gradle"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.Tup")
	assert.Equal(t, LanguageID("tup"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.bzl")
	assert.Equal(t, LanguageID("bazel"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.gyp")
	assert.Equal(t, LanguageID("gyp"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.gypi")
	assert.Equal(t, LanguageID("gyp"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.iss")
	assert.Equal(t, LanguageID("inno setup"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.wixproj")
	assert.Equal(t, LanguageID("wix"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.wxs")
	assert.Equal(t, LanguageID("wix"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.nsh")
	assert.Equal(t, LanguageID("nsis"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.nsi")
	assert.Equal(t, LanguageID("nsis"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("conanfile.txt")
	assert.Equal(t, LanguageID("conan"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("conanfile.py")
	assert.Equal(t, LanguageID("conan"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("conanenv.txt")
	assert.Equal(t, LanguageID("conan"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("sconstruct")
	assert.Equal(t, LanguageID("scons"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("premake4.lua")
	assert.Equal(t, LanguageID("premake"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("premake5.lua")
	assert.Equal(t, LanguageID("premake"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("gulp.js")
	assert.Equal(t, LanguageID("gulp"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("zeusfile.yml")
	assert.Equal(t, LanguageID("zeus"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("bam.lua")
	assert.Equal(t, LanguageID("bam"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("meson.build")
	assert.Equal(t, LanguageID("meson"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("huntergate.cmake")
	assert.Equal(t, LanguageID("hunter"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("hunter.cmake")
	assert.Equal(t, LanguageID("hunter"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("requirements.txt")
	assert.Equal(t, LanguageID("cget"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("meta.yaml")
	assert.Equal(t, LanguageID("conda"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("build.hs")
	assert.Equal(t, LanguageID("shake"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("gemfile")
	assert.Equal(t, LanguageID("gemfile"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("package.json")
	assert.Equal(t, LanguageID("npm"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("webpack.config.js")
	assert.Equal(t, LanguageID("webpack"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("bower.json")
	assert.Equal(t, LanguageID("bower"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("pom.xml")
	assert.Equal(t, LanguageID("maven"), lang)
	assert.Equal(t, DepFileTypeBuildSystem, typ)

	typ, lang = r.GetDepFileTypeAndLanguage(".eslintrc.test")
	assert.Equal(t, LanguageID("eslint"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage(".travis.yml")
	assert.Equal(t, LanguageID("travis"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("appveyor.yml")
	assert.Equal(t, LanguageID("appveyor"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage(".gitlab-ci.yml")
	assert.Equal(t, LanguageID("gitlab"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("circle.yml")
	assert.Equal(t, LanguageID("circleci"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage(".clang-format")
	assert.Equal(t, LanguageID("clangformat"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage(".clang-format")
	assert.Equal(t, LanguageID("clangformat"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage(".clang_complete")
	assert.Equal(t, LanguageID("clang_complete"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage(".editorconfig")
	assert.Equal(t, LanguageID("editorconfig"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage(".gdbinit")
	assert.Equal(t, LanguageID("gdbinit"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage(".yardopts")
	assert.Equal(t, LanguageID("yard"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage(".istanbul.yml")
	assert.Equal(t, LanguageID("istanbul"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage(".codecov.yml")
	assert.Equal(t, LanguageID("codecov.io"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage(".pylintrc")
	assert.Equal(t, LanguageID("pylint"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage(".flake8")
	assert.Equal(t, LanguageID("flake8"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage(".dir-locals.el")
	assert.Equal(t, LanguageID("emacs.dir-locals"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("doxygen.config")
	assert.Equal(t, LanguageID("doxygen"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage(".mention-bot")
	assert.Equal(t, LanguageID("mention-bot"), lang)
	assert.Equal(t, DepFileTypeEnvConfig, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("APACHE-2.0.txt")
	assert.Equal(t, LanguageID("apache-2.0"), lang)
	assert.Equal(t, DepFileTypeLicense, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("GNU-AGPL-3.0.txt")
	assert.Equal(t, LanguageID("agpl-3.0"), lang)
	assert.Equal(t, DepFileTypeLicense, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.s")
	assert.Equal(t, LanguageID("assembly"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.asm")
	assert.Equal(t, LanguageID("assembly"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.c")
	assert.Equal(t, LanguageID("c"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.cpp")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.cc")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.cxx")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.c++")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.h")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.hh")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.hpp")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.hxx")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.h++")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.inc")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.inl")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.ipp")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.tcc")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.tpp")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.txx")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.moc")
	assert.Equal(t, LanguageID("c++"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.cs")
	assert.Equal(t, LanguageID("c#"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.csx")
	assert.Equal(t, LanguageID("c#"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.d")
	assert.Equal(t, LanguageID("d"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.dd")
	assert.Equal(t, LanguageID("d"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.di")
	assert.Equal(t, LanguageID("d"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.f")
	assert.Equal(t, LanguageID("fortran"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.f03")
	assert.Equal(t, LanguageID("fortran"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.f08")
	assert.Equal(t, LanguageID("fortran"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.f77")
	assert.Equal(t, LanguageID("fortran"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.f90")
	assert.Equal(t, LanguageID("fortran"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.f95")
	assert.Equal(t, LanguageID("fortran"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.for")
	assert.Equal(t, LanguageID("fortran"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.fpp")
	assert.Equal(t, LanguageID("fortran"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.go")
	assert.Equal(t, LanguageID("go"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.java")
	assert.Equal(t, LanguageID("java"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.dfm")
	assert.Equal(t, LanguageID("pascal"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.dpr")
	assert.Equal(t, LanguageID("pascal"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.lpr")
	assert.Equal(t, LanguageID("pascal"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.pas")
	assert.Equal(t, LanguageID("pascal"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.pascal")
	assert.Equal(t, LanguageID("pascal"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.al")
	assert.Equal(t, LanguageID("perl"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.perl")
	assert.Equal(t, LanguageID("perl"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.ph")
	assert.Equal(t, LanguageID("perl"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.pl")
	assert.Equal(t, LanguageID("perl"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.plx")
	assert.Equal(t, LanguageID("perl"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.pm")
	assert.Equal(t, LanguageID("perl"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.psgi")
	assert.Equal(t, LanguageID("perl"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.aw")
	assert.Equal(t, LanguageID("php"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.ctp")
	assert.Equal(t, LanguageID("php"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.php")
	assert.Equal(t, LanguageID("php"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.php3")
	assert.Equal(t, LanguageID("php"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.php4")
	assert.Equal(t, LanguageID("php"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.php5")
	assert.Equal(t, LanguageID("php"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.phps")
	assert.Equal(t, LanguageID("php"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.phpt")
	assert.Equal(t, LanguageID("php"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.phtml")
	assert.Equal(t, LanguageID("php"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.lmi")
	assert.Equal(t, LanguageID("python"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.py")
	assert.Equal(t, LanguageID("python"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.py3")
	assert.Equal(t, LanguageID("python"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.pyde")
	assert.Equal(t, LanguageID("python"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.pyp")
	assert.Equal(t, LanguageID("python"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.pyt")
	assert.Equal(t, LanguageID("python"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.pyw")
	assert.Equal(t, LanguageID("python"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.xpy")
	assert.Equal(t, LanguageID("python"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.pyx")
	assert.Equal(t, LanguageID("cython"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.qml")
	assert.Equal(t, LanguageID("qml"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.r")
	assert.Equal(t, LanguageID("r"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.rd")
	assert.Equal(t, LanguageID("r"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.rsx")
	assert.Equal(t, LanguageID("r"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.eye")
	assert.Equal(t, LanguageID("ruby"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.gemspec")
	assert.Equal(t, LanguageID("ruby"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.god")
	assert.Equal(t, LanguageID("ruby"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.irbc")
	assert.Equal(t, LanguageID("ruby"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.rabl")
	assert.Equal(t, LanguageID("ruby"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.rake")
	assert.Equal(t, LanguageID("ruby"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.rb")
	assert.Equal(t, LanguageID("ruby"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.rbuild")
	assert.Equal(t, LanguageID("ruby"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.rbw")
	assert.Equal(t, LanguageID("ruby"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.rbx")
	assert.Equal(t, LanguageID("ruby"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.ru")
	assert.Equal(t, LanguageID("ruby"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.ruby")
	assert.Equal(t, LanguageID("ruby"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.rs")
	assert.Equal(t, LanguageID("rust"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.cql")
	assert.Equal(t, LanguageID("sql"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.ddl")
	assert.Equal(t, LanguageID("sql"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.mysql")
	assert.Equal(t, LanguageID("sql"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.prc")
	assert.Equal(t, LanguageID("sql"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.sql")
	assert.Equal(t, LanguageID("sql"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.tab")
	assert.Equal(t, LanguageID("sql"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.udf")
	assert.Equal(t, LanguageID("sql"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.viw")
	assert.Equal(t, LanguageID("sql"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.vb")
	assert.Equal(t, LanguageID("visual basic"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.vba")
	assert.Equal(t, LanguageID("visual basic"), lang)
	assert.Equal(t, DepFileTypeSource, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.vbs")
	assert.Equal(t, LanguageID("visual basic"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.i")
	assert.Equal(t, LanguageID("swig"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.idl")
	assert.Equal(t, LanguageID("idl"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.proto")
	assert.Equal(t, LanguageID("protocol buffer"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.thrift")
	assert.Equal(t, LanguageID("thrift"), lang)
	assert.Equal(t, DepFileTypeSource, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.fbs")
	assert.Equal(t, LanguageID("flatbuffers"), lang)
	assert.Equal(t, DepFileTypeGenerator, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.capnp")
	assert.Equal(t, LanguageID("cap'n proto"), lang)
	assert.Equal(t, DepFileTypeGenerator, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.l")
	assert.Equal(t, LanguageID("lex"), lang)
	assert.Equal(t, DepFileTypeGenerator, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.lex")
	assert.Equal(t, LanguageID("lex"), lang)
	assert.Equal(t, DepFileTypeGenerator, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.ll")
	assert.Equal(t, LanguageID("lex"), lang)
	assert.Equal(t, DepFileTypeGenerator, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.y")
	assert.Equal(t, LanguageID("yacc"), lang)
	assert.Equal(t, DepFileTypeGenerator, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.yacc")
	assert.Equal(t, LanguageID("yacc"), lang)
	assert.Equal(t, DepFileTypeGenerator, typ)
	typ, lang = r.GetDepFileTypeAndLanguage("test.yxx")
	assert.Equal(t, LanguageID("yacc"), lang)
	assert.Equal(t, DepFileTypeGenerator, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("test.m4")
	assert.Equal(t, LanguageID("m4"), lang)
	assert.Equal(t, DepFileTypeGenerator, typ)

	typ, lang = r.GetDepFileTypeAndLanguage("unknown type")
	assert.Equal(t, LanguageUnknown, lang)
	assert.Equal(t, DepFileTypeUnknown, typ)
}
