[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/atotto/clipboard"

[[constraint]]
  branch = "master"
  name = "github.com/bmizerany/assert"

[[constraint]]
  branch = "master"
  name = "github.com/kballard/go-shellquote"

[[constraint]]
  name = "github.com/mattn/go-colorable"
  version = "0.0.9"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/ogier/pflag"
  version = "0.0.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[prune]
  go-tests = true
  unused-packages = true
